/**
 * Seed script: populates the players collection with IPL 2026 squad data.
 * Source: players_ipl_2026.xlsx (Players sheet)
 * Run once: npm run seed
 * Safe to re-run — uses upsert so no duplicates are created.
 */
require('dotenv').config();
const mongoose = require('mongoose');
const Player = require('./models/Player.model');

const PLAYERS = [
  // ── CSK ──────────────────────────────────────────────────────────────────
  { name: 'Ruturaj Gaikwad', franchise: 'CSK', role: 'BAT', credits: 10 },
  { name: 'MS Dhoni', franchise: 'CSK', role: 'WK', credits: 8 },
  { name: 'Sanju Samson', franchise: 'CSK', role: 'WK', credits: 10 },
  { name: 'Dewald Brevis', franchise: 'CSK', role: 'BAT', credits: 7.5 },
  { name: 'Ayush Mhatre', franchise: 'CSK', role: 'BAT', credits: 6 },
  { name: 'Kartik Sharma', franchise: 'CSK', role: 'WK', credits: 5.5 },
  { name: 'Sarfaraz Khan', franchise: 'CSK', role: 'BAT', credits: 5.5 },
  { name: 'Urvil Patel', franchise: 'CSK', role: 'WK', credits: 6 },
  { name: 'Anshul Kamboj', franchise: 'CSK', role: 'AR', credits: 7.5 },
  { name: 'Jamie Overton', franchise: 'CSK', role: 'AR', credits: 7 },
  { name: 'Ramakrishna Ghosh', franchise: 'CSK', role: 'AR', credits: 6 },
  { name: 'Shivam Dube', franchise: 'CSK', role: 'AR', credits: 9.5 },
  { name: 'Shreyas Gopal', franchise: 'CSK', role: 'AR', credits: 6 },
  { name: 'Khaleel Ahmed', franchise: 'CSK', role: 'BOWL', credits: 8 },
  { name: 'Noor Ahmad', franchise: 'CSK', role: 'BOWL', credits: 9 },
  { name: 'Mukesh Choudhary', franchise: 'CSK', role: 'BOWL', credits: 6 },
  { name: 'Nathan Ellis', franchise: 'CSK', role: 'BOWL', credits: 7.5 },
  { name: 'Gurjapneet Singh', franchise: 'CSK', role: 'BOWL', credits: 7.5 },
  { name: 'Prashant Veer', franchise: 'CSK', role: 'AR', credits: 5.5 },
  { name: 'Matthew Short', franchise: 'CSK', role: 'AR', credits: 5.5 },
  { name: 'Aman Khan', franchise: 'CSK', role: 'AR', credits: 5.5 },
  { name: 'Zak Foulkes', franchise: 'CSK', role: 'AR', credits: 5.5 },
  { name: 'Akeal Hosein', franchise: 'CSK', role: 'BOWL', credits: 5.5 },
  { name: 'Matt Henry', franchise: 'CSK', role: 'BOWL', credits: 5.5 },
  { name: 'Rahul Chahar', franchise: 'CSK', role: 'BOWL', credits: 5.5 },

  // ── DC ───────────────────────────────────────────────────────────────────
  { name: 'KL Rahul', franchise: 'DC', role: 'WK', credits: 9.5 },
  { name: 'Axar Patel', franchise: 'DC', role: 'AR', credits: 9.5 },
  { name: 'Karun Nair', franchise: 'DC', role: 'BAT', credits: 6.5 },
  { name: 'Abhishek Porel', franchise: 'DC', role: 'WK', credits: 8 },
  { name: 'Kuldeep Yadav', franchise: 'DC', role: 'BOWL', credits: 9.5 },
  { name: 'Mitchell Starc', franchise: 'DC', role: 'BOWL', credits: 9 },
  { name: 'Ashutosh Sharma', franchise: 'DC', role: 'AR', credits: 7.5 },
  { name: 'Mukesh Kumar', franchise: 'DC', role: 'BOWL', credits: 8.5 },
  { name: 'Nitish Rana', franchise: 'DC', role: 'AR', credits: 8 },
  { name: 'Sameer Rizvi', franchise: 'DC', role: 'AR', credits: 6.5 },
  { name: 'T. Natarajan', franchise: 'DC', role: 'BOWL', credits: 9 },
  { name: 'Tristan Stubbs', franchise: 'DC', role: 'WK', credits: 9 },
  { name: 'Madhav Tiwari', franchise: 'DC', role: 'AR', credits: 6 },
  { name: 'Ajay Mandal', franchise: 'DC', role: 'AR', credits: 6 },
  { name: 'Tripurana Vijay', franchise: 'DC', role: 'AR', credits: 6 },
  { name: 'Vipraj Nigam', franchise: 'DC', role: 'AR', credits: 6.5 },
  { name: 'David Miller', franchise: 'DC', role: 'BAT', credits: 5.5 },
  { name: 'Pathum Nissanka', franchise: 'DC', role: 'BAT', credits: 5.5 },
  { name: 'Sahil Parakh', franchise: 'DC', role: 'BAT', credits: 5.5 },
  { name: 'Prithvi Shaw', franchise: 'DC', role: 'BAT', credits: 5.5 },
  { name: 'Dushmantha Chameera', franchise: 'DC', role: 'BOWL', credits: 6.5 },
  { name: 'Lungi Ngidi', franchise: 'DC', role: 'BOWL', credits: 5.5 },
  { name: 'Kyle Jamieson', franchise: 'DC', role: 'BOWL', credits: 5.5 },
  { name: 'Auqib Dar', franchise: 'DC', role: 'AR', credits: 5.5 },

  // ── GT ───────────────────────────────────────────────────────────────────
  { name: 'Shubman Gill', franchise: 'GT', role: 'BAT', credits: 9.5 },
  { name: 'Jos Buttler', franchise: 'GT', role: 'WK', credits: 9.5 },
  { name: 'Rashid Khan', franchise: 'GT', role: 'BOWL', credits: 10 },
  { name: 'Mohammad Siraj', franchise: 'GT', role: 'BOWL', credits: 9.5 },
  { name: 'Kagiso Rabada', franchise: 'GT', role: 'BOWL', credits: 9 },
  { name: 'Prasidh Krishna', franchise: 'GT', role: 'BOWL', credits: 9 },
  { name: 'Glenn Phillips', franchise: 'GT', role: 'WK', credits: 7.5 },
  { name: 'Anuj Rawat', franchise: 'GT', role: 'WK', credits: 6 },
  { name: 'Kumar Kushagra', franchise: 'GT', role: 'WK', credits: 6.5 },
  { name: 'Washington Sundar', franchise: 'GT', role: 'AR', credits: 7.5 },
  { name: 'R. Sai Kishore', franchise: 'GT', role: 'AR', credits: 7.5 },
  { name: 'Rahul Tewatia', franchise: 'GT', role: 'AR', credits: 8 },
  { name: 'Sai Sudharsan', franchise: 'GT', role: 'BAT', credits: 8.5 },
  { name: 'Shahrukh Khan', franchise: 'GT', role: 'AR', credits: 8 },
  { name: 'Jayant Yadav', franchise: 'GT', role: 'AR', credits: 6.5 },
  { name: 'Nishant Sindhu', franchise: 'GT', role: 'AR', credits: 6 },
  { name: 'Mohd. Arshad Khan', franchise: 'GT', role: 'AR', credits: 7 },
  { name: 'Gurnoor Singh Brar', franchise: 'GT', role: 'BOWL', credits: 7 },
  { name: 'Manav Suthar', franchise: 'GT', role: 'BOWL', credits: 6 },
  { name: 'Ishant Sharma', franchise: 'GT', role: 'BOWL', credits: 6.5 },
  { name: 'Tom Banton', franchise: 'GT', role: 'WK', credits: 5.5 },
  { name: 'Jason Holder', franchise: 'GT', role: 'AR', credits: 5.5 },
  { name: 'Luke Wood', franchise: 'GT', role: 'BOWL', credits: 5.5 },
  { name: 'Ashok Sharma', franchise: 'GT', role: 'BOWL', credits: 5.5 },
  { name: 'Prithvi Raj Yarra', franchise: 'GT', role: 'BOWL', credits: 5.5 },

  // ── KKR ──────────────────────────────────────────────────────────────────
  { name: 'Ajinkya Rahane', franchise: 'KKR', role: 'BAT', credits: 7 },
  { name: 'Rinku Singh', franchise: 'KKR', role: 'BAT', credits: 9.5 },
  { name: 'Sunil Narine', franchise: 'KKR', role: 'AR', credits: 9.5 },
  { name: 'Varun Chakaravarthy', franchise: 'KKR', role: 'BOWL', credits: 9.5 },
  { name: 'Angkrish Raghuvanshi', franchise: 'KKR', role: 'BAT', credits: 7.5 },
  { name: 'Harshit Rana', franchise: 'KKR', role: 'BOWL', credits: 8 },
  { name: 'Ramandeep Singh', franchise: 'KKR', role: 'AR', credits: 8 },
  { name: 'Rovman Powell', franchise: 'KKR', role: 'BAT', credits: 7 },
  { name: 'Manish Pandey', franchise: 'KKR', role: 'BAT', credits: 6.5 },
  { name: 'Anukul Roy', franchise: 'KKR', role: 'AR', credits: 6 },
  { name: 'Vaibhav Arora', franchise: 'KKR', role: 'BOWL', credits: 7 },
  { name: 'Umran Malik', franchise: 'KKR', role: 'BOWL', credits: 6.5 },
  { name: 'Mohammad Shami', franchise: 'KKR', role: 'BOWL', credits: 9 },
  { name: 'Mitchell Marsh', franchise: 'KKR', role: 'AR', credits: 7.5 },
  { name: 'Cameron Green', franchise: 'KKR', role: 'AR', credits: 5.5 },
  { name: 'Matheesha Pathirana', franchise: 'KKR', role: 'BOWL', credits: 5.5 },
  { name: 'Finn Allen', franchise: 'KKR', role: 'WK', credits: 5.5 },
  { name: 'Tim Seifert', franchise: 'KKR', role: 'WK', credits: 5.5 },
  { name: 'Rachin Ravindra', franchise: 'KKR', role: 'AR', credits: 5.5 },
  { name: 'Rahul Tripathi', franchise: 'KKR', role: 'BAT', credits: 5.5 },
  { name: 'Tejasvi Singh', franchise: 'KKR', role: 'WK', credits: 5.5 },
  { name: 'Sarthak Ranjan', franchise: 'KKR', role: 'AR', credits: 5.5 },
  { name: 'Daksh Kamra', franchise: 'KKR', role: 'AR', credits: 5.5 },
  { name: 'Kartik Tyagi', franchise: 'KKR', role: 'BOWL', credits: 5.5 },
  { name: 'Prashant Solanki', franchise: 'KKR', role: 'BOWL', credits: 5.5 },

  // ── LSG ──────────────────────────────────────────────────────────────────
  { name: 'Rishabh Pant', franchise: 'LSG', role: 'WK', credits: 10 },
  { name: 'Nicholas Pooran', franchise: 'LSG', role: 'WK', credits: 10 },
  { name: 'Aiden Markram', franchise: 'LSG', role: 'BAT', credits: 7.5 },
  { name: 'Mayank Yadav', franchise: 'LSG', role: 'BOWL', credits: 9 },
  { name: 'Avesh Khan', franchise: 'LSG', role: 'BOWL', credits: 9 },
  { name: 'Ayush Badoni', franchise: 'LSG', role: 'AR', credits: 8 },
  { name: 'Abdul Samad', franchise: 'LSG', role: 'AR', credits: 8 },
  { name: 'Shahbaz Ahmed', franchise: 'LSG', role: 'AR', credits: 7.5 },
  { name: 'Arshin Kulkarni', franchise: 'LSG', role: 'AR', credits: 6 },
  { name: 'Matthew Breetzke', franchise: 'LSG', role: 'BAT', credits: 6.5 },
  { name: 'Himmat Singh', franchise: 'LSG', role: 'BAT', credits: 6 },
  { name: 'Manimaran Siddharth', franchise: 'LSG', role: 'BOWL', credits: 6.5 },
  { name: 'Digvesh Rathi', franchise: 'LSG', role: 'BOWL', credits: 6 },
  { name: 'Akash Singh', franchise: 'LSG', role: 'BOWL', credits: 6 },
  { name: 'Arjun Tendulkar', franchise: 'LSG', role: 'BOWL', credits: 6 },
  { name: 'Prince Yadav', franchise: 'LSG', role: 'BOWL', credits: 6 },
  { name: 'Mohsin Khan', franchise: 'LSG', role: 'BOWL', credits: 8 },
  { name: 'Mitchell Marsh', franchise: 'LSG', role: 'AR', credits: 7.5 },
  { name: 'Mohammad Shami', franchise: 'LSG', role: 'BOWL', credits: 9 },
  { name: 'Wanindu Hasaranga', franchise: 'LSG', role: 'AR', credits: 5.5 },
  { name: 'Josh Inglis', franchise: 'LSG', role: 'WK', credits: 5.5 },
  { name: 'Anrich Nortje', franchise: 'LSG', role: 'BOWL', credits: 5.5 },
  { name: 'Naman Tiwari', franchise: 'LSG', role: 'BOWL', credits: 5.5 },
  { name: 'Mukul Choudhary', franchise: 'LSG', role: 'WK', credits: 5.5 },
  { name: 'Akshat Raghuwanshi', franchise: 'LSG', role: 'BAT', credits: 5.5 },

  // ── MI ───────────────────────────────────────────────────────────────────
  { name: 'Rohit Sharma', franchise: 'MI', role: 'BAT', credits: 9.5 },
  { name: 'Hardik Pandya', franchise: 'MI', role: 'AR', credits: 9.5 },
  { name: 'Jasprit Bumrah', franchise: 'MI', role: 'BOWL', credits: 10 },
  { name: 'Suryakumar Yadav', franchise: 'MI', role: 'BAT', credits: 9.5 },
  { name: 'Trent Boult', franchise: 'MI', role: 'BOWL', credits: 9.5 },
  { name: 'Tilak Varma', franchise: 'MI', role: 'BAT', credits: 8.5 },
  { name: 'Deepak Chahar', franchise: 'MI', role: 'BOWL', credits: 9 },
  { name: 'Will Jacks', franchise: 'MI', role: 'AR', credits: 8 },
  { name: 'Naman Dhir', franchise: 'MI', role: 'AR', credits: 8 },
  { name: 'Shardul Thakur', franchise: 'MI', role: 'AR', credits: 7.5 },
  { name: 'Mitchell Santner', franchise: 'MI', role: 'AR', credits: 7.5 },
  { name: 'Ryan Rickelton', franchise: 'MI', role: 'WK', credits: 7 },
  { name: 'Corbin Bosch', franchise: 'MI', role: 'AR', credits: 6.5 },
  { name: 'Sherfane Rutherford', franchise: 'MI', role: 'BAT', credits: 7.5 },
  { name: 'Robin Minz', franchise: 'MI', role: 'WK', credits: 6.5 },
  { name: 'Raj Angad Bawa', franchise: 'MI', role: 'AR', credits: 6 },
  { name: 'Mayank Markande', franchise: 'MI', role: 'BOWL', credits: 6 },
  { name: 'Raghu Sharma', franchise: 'MI', role: 'BOWL', credits: 6 },
  { name: 'Ashwani Kumar', franchise: 'MI', role: 'BOWL', credits: 6 },
  { name: 'Quinton de Kock', franchise: 'MI', role: 'WK', credits: 5.5 },
  { name: 'Atharva Ankolekar', franchise: 'MI', role: 'AR', credits: 5.5 },
  { name: 'Mayank Rawat', franchise: 'MI', role: 'AR', credits: 5.5 },
  { name: 'Danish Malewar', franchise: 'MI', role: 'BAT', credits: 5.5 },
  { name: 'Mohammad Izhar', franchise: 'MI', role: 'BOWL', credits: 5.5 },

  // ── PBKS ─────────────────────────────────────────────────────────────────
  { name: 'Shreyas Iyer', franchise: 'PBKS', role: 'BAT', credits: 10 },
  { name: 'Arshdeep Singh', franchise: 'PBKS', role: 'BOWL', credits: 10 },
  { name: 'Marcus Stoinis', franchise: 'PBKS', role: 'AR', credits: 9 },
  { name: 'Marco Jansen', franchise: 'PBKS', role: 'AR', credits: 8.5 },
  { name: 'Yuzvendra Chahal', franchise: 'PBKS', role: 'BOWL', credits: 10 },
  { name: 'Nehal Wadhera', franchise: 'PBKS', role: 'BAT', credits: 8 },
  { name: 'Prabhsimran Singh', franchise: 'PBKS', role: 'WK', credits: 8 },
  { name: 'Shashank Singh', franchise: 'PBKS', role: 'AR', credits: 8 },
  { name: 'Priyansh Arya', franchise: 'PBKS', role: 'AR', credits: 7.5 },
  { name: 'Harpreet Brar', franchise: 'PBKS', role: 'AR', credits: 7 },
  { name: 'Lockie Ferguson', franchise: 'PBKS', role: 'BOWL', credits: 7.5 },
  { name: 'Mitch Owen', franchise: 'PBKS', role: 'AR', credits: 7.5 },
  { name: 'Azmatullah Omarzai', franchise: 'PBKS', role: 'AR', credits: 7.5 },
  { name: 'Musheer Khan', franchise: 'PBKS', role: 'AR', credits: 6 },
  { name: 'Harnoor Pannu', franchise: 'PBKS', role: 'BAT', credits: 6 },
  { name: 'Pyla Avinash', franchise: 'PBKS', role: 'BAT', credits: 6 },
  { name: 'Suryansh Shedge', franchise: 'PBKS', role: 'AR', credits: 6 },
  { name: 'Vishnu Vinod', franchise: 'PBKS', role: 'WK', credits: 6.5 },
  { name: 'Vyshak Vijaykumar', franchise: 'PBKS', role: 'BOWL', credits: 7 },
  { name: 'Yash Thakur', franchise: 'PBKS', role: 'BOWL', credits: 7 },
  { name: 'Xavier Bartlett', franchise: 'PBKS', role: 'BOWL', credits: 6.5 },
  { name: 'Cooper Connolly', franchise: 'PBKS', role: 'AR', credits: 5.5 },
  { name: 'Ben Dwarshuis', franchise: 'PBKS', role: 'AR', credits: 5.5 },
  { name: 'Pravin Dubey', franchise: 'PBKS', role: 'BOWL', credits: 5.5 },
  { name: 'Vishal Nishad', franchise: 'PBKS', role: 'BOWL', credits: 5.5 },

  // ── RR ───────────────────────────────────────────────────────────────────
  { name: 'Yashasvi Jaiswal', franchise: 'RR', role: 'BAT', credits: 10 },
  { name: 'Riyan Parag', franchise: 'RR', role: 'AR', credits: 9.5 },
  { name: 'Ravindra Jadeja', franchise: 'RR', role: 'AR', credits: 9.5 },
  { name: 'Jofra Archer', franchise: 'RR', role: 'BOWL', credits: 9.5 },
  { name: 'Shimron Hetmyer', franchise: 'RR', role: 'BAT', credits: 9 },
  { name: 'Sam Curran', franchise: 'RR', role: 'AR', credits: 7.5 },
  { name: 'Dhruv Jurel', franchise: 'RR', role: 'WK', credits: 9.5 },
  { name: 'Tushar Deshpande', franchise: 'RR', role: 'BOWL', credits: 8.5 },
  { name: 'Sandeep Sharma', franchise: 'RR', role: 'BOWL', credits: 8 },
  { name: 'Kwena Maphaka', franchise: 'RR', role: 'BOWL', credits: 7 },
  { name: 'Donovan Ferreira', franchise: 'RR', role: 'WK', credits: 7 },
  { name: 'Vaibhav Suryavanshi', franchise: 'RR', role: 'BAT', credits: 7 },
  { name: 'Shubham Dubey', franchise: 'RR', role: 'BAT', credits: 6.5 },
  { name: 'Lhuan-dre Pretorius', franchise: 'RR', role: 'AR', credits: 6 },
  { name: 'Yudhvir Charak', franchise: 'RR', role: 'AR', credits: 6 },
  { name: 'Nandre Burger', franchise: 'RR', role: 'BOWL', credits: 7.5 },
  { name: 'Ravi Bishnoi', franchise: 'RR', role: 'BOWL', credits: 5.5 },
  { name: 'Sushant Mishra', franchise: 'RR', role: 'BOWL', credits: 5.5 },
  { name: 'Kuldeep Sen', franchise: 'RR', role: 'BOWL', credits: 5.5 },
  { name: 'Adam Milne', franchise: 'RR', role: 'BOWL', credits: 5.5 },
  { name: 'Ravi Singh', franchise: 'RR', role: 'BAT', credits: 5.5 },
  { name: 'Aman Rao Perala', franchise: 'RR', role: 'BAT', credits: 5.5 },
  { name: 'Yash Raj Punia', franchise: 'RR', role: 'BOWL', credits: 5.5 },
  { name: 'Vignesh Puthur', franchise: 'RR', role: 'BOWL', credits: 5.5 },
  { name: 'Brijesh Sharma', franchise: 'RR', role: 'BOWL', credits: 5.5 },

  // ── RCB ──────────────────────────────────────────────────────────────────
  { name: 'Virat Kohli', franchise: 'RCB', role: 'BAT', credits: 10 },
  { name: 'Rajat Patidar', franchise: 'RCB', role: 'BAT', credits: 9 },
  { name: 'Phil Salt', franchise: 'RCB', role: 'WK', credits: 9 },
  { name: 'Bhuvneshwar Kumar', franchise: 'RCB', role: 'BOWL', credits: 9 },
  { name: 'Josh Hazlewood', franchise: 'RCB', role: 'BOWL', credits: 9.5 },
  { name: 'Devdutt Padikkal', franchise: 'RCB', role: 'BAT', credits: 7.5 },
  { name: 'Jitesh Sharma', franchise: 'RCB', role: 'WK', credits: 9 },
  { name: 'Krunal Pandya', franchise: 'RCB', role: 'AR', credits: 8 },
  { name: 'Tim David', franchise: 'RCB', role: 'AR', credits: 7.5 },
  { name: 'Yash Dayal', franchise: 'RCB', role: 'BOWL', credits: 8 },
  { name: 'Rasikh Dar', franchise: 'RCB', role: 'BOWL', credits: 8.5 },
  { name: 'Suyash Sharma', franchise: 'RCB', role: 'BOWL', credits: 7.5 },
  { name: 'Jacob Bethell', franchise: 'RCB', role: 'AR', credits: 7.5 },
  { name: 'Nuwan Thushara', franchise: 'RCB', role: 'BOWL', credits: 7 },
  { name: 'Romario Shepherd', franchise: 'RCB', role: 'AR', credits: 7 },
  { name: 'Swapnil Singh', franchise: 'RCB', role: 'AR', credits: 6.5 },
  { name: 'Abhinandan Singh', franchise: 'RCB', role: 'BOWL', credits: 6 },
  { name: 'Jordan Cox', franchise: 'RCB', role: 'WK', credits: 5.5 },
  { name: 'Venkatesh Iyer', franchise: 'RCB', role: 'AR', credits: 5.5 },
  { name: 'Jacob Duffy', franchise: 'RCB', role: 'BOWL', credits: 5.5 },
  { name: 'Satvik Deswal', franchise: 'RCB', role: 'AR', credits: 5.5 },
  { name: 'Mangesh Yadav', franchise: 'RCB', role: 'AR', credits: 5.5 },
  { name: 'Vicky Ostwal', franchise: 'RCB', role: 'BOWL', credits: 5.5 },
  { name: 'Vihaan Malhotra', franchise: 'RCB', role: 'AR', credits: 5.5 },
  { name: 'Kanishk Chouhan', franchise: 'RCB', role: 'AR', credits: 5.5 },

  // ── SRH ──────────────────────────────────────────────────────────────────
  { name: 'Abhishek Sharma', franchise: 'SRH', role: 'AR', credits: 9.5 },
  { name: 'Pat Cummins', franchise: 'SRH', role: 'BOWL', credits: 10 },
  { name: 'Travis Head', franchise: 'SRH', role: 'BAT', credits: 9.5 },
  { name: 'Heinrich Klaasen', franchise: 'SRH', role: 'WK', credits: 10 },
  { name: 'Ishan Kishan', franchise: 'SRH', role: 'WK', credits: 9 },
  { name: 'Harshal Patel', franchise: 'SRH', role: 'AR', credits: 8.5 },
  { name: 'Nitish Kumar Reddy', franchise: 'SRH', role: 'AR', credits: 8.5 },
  { name: 'Kamindu Mendis', franchise: 'SRH', role: 'AR', credits: 6.5 },
  { name: 'Brydon Carse', franchise: 'SRH', role: 'AR', credits: 7 },
  { name: 'Eshan Malinga', franchise: 'SRH', role: 'BOWL', credits: 7 },
  { name: 'Harsh Dubey', franchise: 'SRH', role: 'AR', credits: 6 },
  { name: 'Jaydev Unadkat', franchise: 'SRH', role: 'BOWL', credits: 7 },
  { name: 'Aniket Verma', franchise: 'SRH', role: 'BAT', credits: 6 },
  { name: 'Smaran Ravichandran', franchise: 'SRH', role: 'BAT', credits: 6 },
  { name: 'Zeeshan Ansari', franchise: 'SRH', role: 'BOWL', credits: 6 },
  { name: 'Liam Livingstone', franchise: 'SRH', role: 'AR', credits: 5.5 },
  { name: 'Jack Edwards', franchise: 'SRH', role: 'AR', credits: 5.5 },
  { name: 'Shivang Kumar', franchise: 'SRH', role: 'AR', credits: 5.5 },
  { name: 'Krains Fuletra', franchise: 'SRH', role: 'AR', credits: 5.5 },
  { name: 'Salil Arora', franchise: 'SRH', role: 'WK', credits: 5.5 },
  { name: 'Sakib Hussain', franchise: 'SRH', role: 'BOWL', credits: 5.5 },
  { name: 'Onkar Tarmale', franchise: 'SRH', role: 'BOWL', credits: 5.5 },
  { name: 'Amit Kumar', franchise: 'SRH', role: 'BOWL', credits: 5.5 },
  { name: 'Praful Hinge', franchise: 'SRH', role: 'BOWL', credits: 5.5 },
  { name: 'Shivam Mavi', franchise: 'SRH', role: 'BOWL', credits: 5.5 },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected to MongoDB');

  let created = 0;
  let skipped = 0;

  for (const p of PLAYERS) {
    const exists = await Player.findOne({ name: p.name, franchise: p.franchise });
    if (!exists) {
      await Player.create(p);
      created++;
    } else {
      skipped++;
    }
  }

  console.log(`✅ Seeded ${created} players (${skipped} already existed)`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
